### ISSUE TITLE
Syntax highlighting for linear-gradient in sass is weird

### ISSUE THREAD

**Issue by realsrikar** [Yummygum/city-lights-syntax-atom#11]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/30674879/32705839-46f3c1ee-c7e6-11e7-9cdb-a1a847318f04.png">

It only affects .sass files as far as tested. I've tested this for the following files types: 
- SASS
- SCSS
- CSS
- Less
- Stylus (.styl) (not supported in City Lights)

**Comment by noudadrichem** [comment]
Hi @realsrikar,

I'll take a look at it, glad you noticed.
Sincerely

**Comment by noudadrichem** [comment]
Hi @realsrikar,

I'll close this issue because the screenshot you provided is not scss/sass or less. We do indeed not support .styl files.

Sincerely
