### ISSUE TITLE
Project license does not follow the Open Source Definition

### ISSUE THREAD

**Issue by Calinou** [Yummygum/city-lights-syntax-atom#12]
As seen [here](https://github.com/Yummygum/city-lights-syntax-atom#license), this project is currently under CC BY-NC-ND 4.0, which is not a [free culture license](https://freedomdefined.org/Licenses/NC) – it also doesn't follow the [Open Source Definition](https://opensource.org/osd/).

I would strongly advise choosing a license such as the [MIT license](https://choosealicense.com/licenses/mit/) instead, as this repository also contains software (which shouldn't be put under Creative Commons licenses, other than [CC0](https://creativecommons.org/publicdomain/zero/1.0/)).

**Comment by noudadrichem** [comment]
Hi @Calinou,

This is something we know.

Sincerely
