### ISSUE TITLE
can't use in Mac

### ISSUE THREAD

**Issue by xylong** [Yummygum/city-lights-syntax-atom#14]
this syntax can't use in MacBook

**Comment by noudadrichem** [comment]
Hi @xylong,

Can you be a bit more specific? e.g. MacOS version, Atom version.
I'm using a MacBook myself, and don't have any problems.

Sincerely.

**Comment by xylong** [comment]
it's ok now, it's just that I make a configuration error

**Comment by noudadrichem** [comment]
Glad you fixed it! @xylong
