### ISSUE TITLE
Deprecated selector in `city-lights-syntax\index.less`

### ISSUE THREAD

**Issue by jonasfrede** [Yummygum/city-lights-syntax-atom#18]
Hey guys, Atom just informed me of the following deprecation: 

> In `city-lights-syntax\index.less`: 

> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

> * `atom-text-editor::shadow .horizontal-scrollbar,
atom-text-editor::shadow .vertical-scrollbar` => `atom-text-editor.editor .horizontal-scrollbar,
atom-text-editor.editor .vertical-scrollbar`

> * `atom-text-editor::shadow .horizontal-scrollbar:hover` => `atom-text-editor.editor .horizontal-scrollbar:hover`

> * `atom-text-editor::shadow .vertical-scrollbar:hover` => `atom-text-editor.editor .vertical-scrollbar:hover`

> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by noudadrichem** [comment]
Hi @jonasfrede,

I see, I'll try to fix this asap! startup time is important. 😝

**Comment by jonasfrede** [comment]
Thanks a lot @noudadrichem! Looks like a quick one to fix, but I was unsure about doing it myself. Hope it doesn't bother you too much. 

Haha, yeah. Shaving off those ~200ms (for me at least) seems really urgent. 😜

**Comment by noudadrichem** [comment]
Should be fixed now! (1.1.8)

Haha, yeay. The less time the better!
