### ISSUE TITLE
Deprecated selector in `city-lights-syntax/index.less`

### ISSUE THREAD

**Issue by mnmalist** [Yummygum/city-lights-syntax-atom#19]
In `city-lights-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .horizontal-scrollbar,
atom-text-editor::shadow .vertical-scrollbar` => `atom-text-editor.editor .horizontal-scrollbar,
atom-text-editor.editor .vertical-scrollbar`

* `atom-text-editor::shadow .horizontal-scrollbar:hover` => `atom-text-editor.editor .horizontal-scrollbar:hover`

* `atom-text-editor::shadow .vertical-scrollbar:hover` => `atom-text-editor.editor .vertical-scrollbar:hover`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jonasfrede** [comment]
Try updating again, should be fixed in 1.1.8.

**Comment by mnmalist** [comment]
It is, thank you.

**Comment by noudadrichem** [comment]
Yup It's fixed! @jonasfrede was quick with reporting it, So I was quick with fixing it. 😝
