### ISSUE TITLE
Atom - Find - Found text highlight hard to see

### ISSUE THREAD

**Issue by Vivalldi** [Yummygum/city-lights-syntax-atom#21]
When searching for text in a file the "highlighted" text is not easy to see. 
![screen shot 2018-03-05 at 4 23 00 pm](https://user-images.githubusercontent.com/8962537/37000479-88ccb66c-2091-11e8-93d4-5a3a9a48057b.png)

In the above example the actual selected `if` is the first one and has a black background. The second `if` is just one that has been found but is not the current one

**Comment by noudadrichem** [comment]
Hi @Vivalldi,

This is intended behavior, chosen by the designer. You could change the highlight settings in 'your stylesheet' under `settings → themes → your stylesheet`
