### ISSUE TITLE
Comment text is poor visibility

### ISSUE THREAD

**Issue by bmf-san** [Yummygum/city-lights-syntax-atom#24]
Thank you for your nice syntax theme.
I love to use it.

However, I have a problem with comment text color.
I think there is poor visibility.

![screen shot 2018-10-09 at 12 40 17](https://user-images.githubusercontent.com/13291041/46645588-8b897180-cbc0-11e8-91a1-414b61a9e99f.png)

Could you please brighten the comment text color?

**Comment by noudadrichem** [comment]
Hi @bmf-san 

That is possible, although the way it is now is a choice of design. 
You're able to edit 'your stylesheet' in `settings → themes → your stylesheet` 
Than if you add thisi snippet:
```
.syntax--comment {
  color: #718ca1 !important;
}
```

You get a lighter comment color from the City Lights color pallet. Like this: 
![image](https://user-images.githubusercontent.com/16288476/46655385-ca60fc80-cbab-11e8-8675-7db858c066f2.png)


Other grayscale colors from the pallete are:
#718ca1
#41505e
#333f4a

I hope I helped

Sincerely,

Noud

**Comment by bmf-san** [comment]
Hi @noudadrichem 
Thank you for your polite comment.
I understood.
I'll try to do it.
