### ISSUE TITLE
Contrast is too low

### ISSUE THREAD

**Issue by nickdima** [Yummygum/city-lights-syntax-atom#6]
The syntax and UI themes are very beautiful but unfortunately I think that the color contrast if very low. After using them for a couple of days I found it that my eyes get really tiered.
Sorry, I don't want to complain, I'm sure a lot of work has been put into it.

**Comment by noudadrichem** [comment]
Hi @nickdima,

May I ask what languages do you write? We mostly optimized it for popular languages like JS/SCSS/XM/PHP

Unfortunate that you don't like the theme, did you try to brighten up the default color?

Sincerely

**Comment by noudadrichem** [comment]
@nickdima,

Perhaps try this: 
```scss
atom-text-editor {
  color: #B7C5D3 !important;
}

```

You can also add the classnames of the things you like to have a brighter default color.😊
