### ISSUE TITLE
url's are not underlined

### ISSUE THREAD

**Issue by luukk** [Yummygum/city-lights-syntax-atom#7]
It would increase readability if url's are underlined.

![screenshot from 2017-11-08 17-34-16](https://user-images.githubusercontent.com/10143385/32560907-196fdc14-c4ab-11e7-8b84-85a31631e7c1.png)

**Comment by noudadrichem** [comment]
Hey @luukk,

Hier is voor gekozen, je zou eventueel in je eigen stylesheet (settings → themes → your stylesheet) je hyperlinks kunnen underlinen, see: http://blog.atom.io/2014/03/03/styling-hyperlinks.html voor wat uitleg.
