### ISSUE TITLE
inconsistent syntax highlighting on class name and constructors

### ISSUE THREAD

**Issue by luukk** [Yummygum/city-lights-syntax-atom#8]
It would be nice if all class related keywords are put to one color. I prefer the `@color4light` so you have a clear distinction with functions.

![screenshot from 2017-11-08 18-18-45](https://user-images.githubusercontent.com/10143385/32563392-71bd62a0-c4b1-11e7-9210-e41d4f5045de.png)

**Comment by noudadrichem** [comment]
Hey @luukk,

This is very true. Ga het aanpassen dankjewel!

**Comment by noudadrichem** [comment]
![image](https://user-images.githubusercontent.com/16288476/34829593-81d0de80-f6e1-11e7-8e7b-700ef6e7a0c1.png)

Fixed!
